name: PyLab4NetCDF
channels:
  - conda-forge
dependencies:
  - notebook
  - jupyterlab
  - bokeh
  - python
  - numpy
  - matplotlib
  - basemap
  - cartopy
  - scipy
  - pip
  - pip:
    - jupyter-server-proxy
    - jupyter-offlinenotebook
    - requests
    - ftputil
    - motuclient
    - netCDF4
    - csv342
    - pandas
    - xarray 
    - shapely>=1.6.4.post1
    - fiona>=1.8.4
    - pyshp
    - cdo
    - moviepy
    - scikit-learn
    - natsort
    - basemap-data-hires
    
  
